In [ ]:
import numpy as np

In [ ]:
l = [ 1 , 4 , 6 , 8]  # convert list to numpy array
l

[1, 4, 6, 8]

In [ ]:
arr = np.array(1)   # create a numpy array with a single element
print(arr)

1


In [ ]:
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) # create a 3x3 matrix
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a2 = np.zeros(5)  # create an array of zeros with length 5
a2

array([0., 0., 0., 0., 0.])

In [ ]:
a3 = np.ones(5)  # create an array of ones with length 5
a3

array([1., 1., 1., 1., 1.])

# Identity Matrix
# cross Zero

In [ ]:
a4 = np.eye(3)   # create a 3x3 identity matrix
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar1 = np.zeros([3 , 3])  # create a 3x3 array of zeros
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar2 = np.ones([3 , 3])  # create a 3x3 array of ones
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ar3 = np.arange(10)  # create an array with values from 0 to 9
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar4 = np.arange(1 , 11)  # create an array with values from 1 to 10
ar4 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar5 = np.arange(1 , 20 , 2)  # create an array with values from 1 to 19 with a step of 2
ar5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
ar6 = np.linspace(1 , 10 , 5) # create an array of 5 values evenly spaced between 1 and 10
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
ar7 = np.full(5 , 2)  # create an array of length 5 filled with the value 2
ar7

array([2, 2, 2, 2, 2])

In [ ]:
ar8 = np.full((3 , 3) , 9)  # create a 3x3 array filled with the value 9
ar8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:

r1 = np.random.rand(3 , 3)  # create a 3x3 array with random values between 0 and 1
r1 

array([[0.38611385, 0.16125816, 0.09756242],
       [0.20136473, 0.42335319, 0.87149353],
       [0.72107912, 0.94826196, 0.9855678 ]])

In [ ]:
r2 = np.random.rand(5) # create an array of length 5 with random values between 0 and 1
r2

array([0.14585906, 0.41994179, 0.02567387, 0.71526218, 0.6563769 ])

In [ ]:
r3 = np.random.randint(5) # create a single random integer between 0 and 4
r3

0

In [ ]:
r4 = np.random.randint(3, 10) # create a single random integer between 3 and 9
r4

6

In [ ]:
r5 = np.random.randint(3 ,10 ,5) # create an array of 5 random integers between 3 and 9
r5

array([6, 5, 9, 8, 9], dtype=int32)

In [ ]:
r6 = np.random.randint(3 , 10 ,(3,3)) # create a 3x3 array of random integers between 3 and 9
r6

array([[3, 9, 7],
       [4, 8, 7],
       [5, 9, 7]], dtype=int32)

# Indexing Of Array

In [ ]:
a2 = np.random.randint(3 , 10 ,(3,3)) # create a 3x3 array of random integers between 3 and 9
a2

array([[5, 7, 8],
       [7, 6, 9],
       [8, 5, 8]], dtype=int32)

In [ ]:
print(a2[0 , 1]) # access element at row 0, column 1

7


In [ ]:
print(a2[2 , 0]) # access element at row 2, column 0

8


In [ ]:
print(a2[2 , 1]) # access element at row 2, column 1

5


In [ ]:
print(a2[0 , 0]) # access element at row 0, column 0

5


# Slicing On Array

In [ ]:
a = np.arange(3 , 10) # create an array with values from 3 to 9
a

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0:3] # slice the array to get elements from index 0 to 2

array([3, 4, 5])

In [ ]:
a[-1:-5:-1] # slice the array to get the last 4 elements in reverse order

array([9, 8, 7, 6])

In [ ]:
a[2:6]  # slice the array to get elements from index 2 to 5

array([5, 6, 7, 8])

In [ ]:
a[0:] # slice the array to get all elements from index 0 to the end

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0::2]  # slice the array to get every second element starting from index 0    

array([3, 5, 7, 9])

In [ ]:
a[::1] # slice the array to get all elements with a step of 1

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2 = np.random.randint(1 , 10 , (3,3)) # create a 3x3 array of random integers between 1 and 9
a2

array([[1, 5, 7],
       [8, 2, 2],
       [1, 9, 7]], dtype=int32)

In [ ]:
a2 [0:2 , 2] # slice the array to get elements from rows 0 to 1 in column 2

array([7, 2], dtype=int32)

In [ ]:
a2 [0: , 1] # slice the array to get all rows in column 1

array([5, 2, 9], dtype=int32)

In [ ]:
a2 [1 , 0:2] # slice the array to get elements from columns 0 to 1 in row 1

array([8, 2], dtype=int32)

In [ ]:
a2 [0: , 1:] # slice the array to get all rows and columns from index 1 to the end

array([[5, 7],
       [2, 2],
       [9, 7]], dtype=int32)

# Shape , Size and Datatype of Array

In [ ]:
a
print(a.shape) # print the shape of the array

(7,)


In [ ]:
a2
print(a2.shape) # print the shape of the 2D array

(3, 3)


In [ ]:
print(a2.size) # print the total number of elements in the 2D array

9


In [ ]:
print(a.size) # print the total number of elements in the array

7


In [ ]:
print(a.dtype)  # print the data type of the elements in the array

int64


In [ ]:
print(a2.dtype) # print the data type of the elements in the 2D array

int32
