In [ ]:
import numpy as np

In [2]:
l = [ 1 , 4 , 6 , 8]
l

[1, 4, 6, 8]

In [5]:
arr = np.array(1)
print(arr)

1


In [ ]:
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a2 = np.zeros(5)
a2

array([0., 0., 0., 0., 0.])

In [6]:
a3 = np.ones(5)
a3

array([1., 1., 1., 1., 1.])

# Identity Matrix
# cross Zero

In [7]:
a4 = np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
ar1 = np.zeros([3 , 3])
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ar2 = np.ones([3 , 3])
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ar3 = np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ar4 = np.arange(1 , 11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
ar5 = np.arange(1 , 20 , 2)
ar5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
ar6 = np.linspace(1 , 10 , 5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
ar7 = np.full(5 , 2)
ar7

array([2, 2, 2, 2, 2])

In [17]:
ar8 = np.full((3 , 3) , 9)
ar8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:

r1 = np.random.rand(3 , 3)
r1 

array([[0.38611385, 0.16125816, 0.09756242],
       [0.20136473, 0.42335319, 0.87149353],
       [0.72107912, 0.94826196, 0.9855678 ]])

In [19]:
r2 = np.random.rand(5)
r2

array([0.14585906, 0.41994179, 0.02567387, 0.71526218, 0.6563769 ])

In [21]:
r3 = np.random.randint(5)
r3

0

In [22]:
r4 = np.random.randint(3, 10)
r4

6

In [23]:
r5 = np.random.randint(3 ,10 ,5)
r5

array([6, 5, 9, 8, 9], dtype=int32)

In [25]:
r6 = np.random.randint(3 , 10 ,(3,3))
r6

array([[3, 9, 7],
       [4, 8, 7],
       [5, 9, 7]], dtype=int32)

# Indexing Of Array

In [32]:
a2 = np.random.randint(3 , 10 ,(3,3))
a2

array([[5, 7, 8],
       [7, 6, 9],
       [8, 5, 8]], dtype=int32)

In [33]:
print(a2[0 , 1])

7


In [38]:
print(a2[2 , 0])

8


In [40]:
print(a2[2 , 1])

5


In [41]:
print(a2[0 , 0])

5


# Slicing On Array

In [45]:
a = np.arange(3 , 10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [46]:
a[0:3]

array([3, 4, 5])

In [47]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [48]:
a[2:6]

array([5, 6, 7, 8])

In [49]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
a[0::2]

array([3, 5, 7, 9])

In [ ]:
a[::1]

array([3, 4, 5, 6, 7, 8, 9])

In [52]:
a2 = np.random.randint(1 , 10 , (3,3))
a2

array([[1, 5, 7],
       [8, 2, 2],
       [1, 9, 7]], dtype=int32)

In [53]:
a2 [0:2 , 2]

array([7, 2], dtype=int32)

In [ ]:
a2 [0: , 1]

array([5, 2, 9], dtype=int32)

In [55]:
a2 [1 , 0:2]

array([8, 2], dtype=int32)

In [56]:
a2 [0: , 1:]

array([[5, 7],
       [2, 2],
       [9, 7]], dtype=int32)

# Shape , Size and Datatype of Array

In [57]:
a
print(a.shape)

(7,)


In [58]:
a2
print(a2.shape)

(3, 3)


In [59]:
print(a2.size)

9


In [60]:
print(a.size)

7


In [61]:
print(a.dtype)

int64


In [62]:
print(a2.dtype)

int32
