## Methemetical Operation

In [ ]:
import numpy as np
a1 = np.array([1 , 5 , 7 , 3 , 5 , 2 ]) # create a 1D numpy array
a1

array([1, 5, 7, 3, 5, 2])

In [ ]:
a2 = ([2 , 4 , 5 , 9 , 8 , 3]) # create a 2D numpy array
a2

[2, 4, 5, 9, 8, 3]

In [ ]:
a1 + a2 # element-wise addition of two arrays

array([ 3,  9, 12, 12, 13,  5])

In [ ]:
a1 - a2 # element-wise subtraction of two arrays

array([-1,  1,  2, -6, -3, -1])

In [ ]:
a1 * a2 # element-wise multiplication of two arrays

array([ 2, 20, 35, 27, 40,  6])

In [ ]:
a1 / a2 # element-wise division of two arrays

array([0.5       , 1.25      , 1.4       , 0.33333333, 0.625     ,
       0.66666667])

In [ ]:
ans = a1 ** 2 # element-wise square of the array

array([ 1, 25, 49,  9, 25,  4])

In [ ]:
np.sqrt(ans)   # both are same sqrt / **2

array([1., 5., 7., 3., 5., 2.])

In [ ]:
a3 = np.array([1.2 , 2.5 , 3.7 , 4.9]) # create a 1D numpy array with float values
a3

array([1.2, 2.5, 3.7, 4.9])

In [ ]:
np.floor(a3) # floor value

array([1., 2., 3., 4.])

In [ ]:
np.ceil(a3) # ceiling value

array([2., 3., 4., 5.])

In [ ]:
np.round(a3) # round off value

array([1., 2., 4., 5.])

## Comining Arrays

In [16]:
a1

array([1, 5, 7, 3, 5, 2])

In [17]:
a2

[2, 4, 5, 9, 8, 3]

In [ ]:
np.concatenate((a1 , a2))    # concatenate two arrays

array([1, 5, 7, 3, 5, 2, 2, 4, 5, 9, 8, 3])

In [20]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create a 2D numpy array
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]) # create another 2D numpy array
arr1
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
np.vstack((arr1 , arr2))