In [1]:
import numpy as np

### Boolean indexing(Filtering Array)

In [2]:
arr = np.array([10, 15, 20, 25, 30])

In [3]:
arr[True]

array([[10, 15, 20, 25, 30]])

In [4]:
l = [True, False, True, False, True]
l

[True, False, True, False, True]

In [6]:
arr[l]

array([10, 20, 30])

In [7]:
arr

array([10, 15, 20, 25, 30])

In [9]:
l2 = (arr%2==0)
l2

array([ True, False,  True, False,  True])

In [10]:
arr[l2]

array([10, 20, 30])

In [11]:
arr[arr % 2 == 0]

array([10, 20, 30])

In [12]:
age = np.array([22, 25, 18, 20, 10, 30, 16])
age

array([22, 25, 18, 20, 10, 30, 16])

In [13]:
age[age > 18]

array([22, 25, 20, 30])

In [ ]:
age[age == 18]

array([18])

In [16]:
a2 = np.array([[3, 5, 7], [4, 7, 9], [6, 1, 2]])
a2

array([[3, 5, 7],
       [4, 7, 9],
       [6, 1, 2]])

In [17]:
l1 = [True, False, True]

In [18]:
a2[l1]

array([[3, 5, 7],
       [6, 1, 2]])

### Boolean Mask(Masking Array)

In [19]:
arr

array([10, 15, 20, 25, 30])

In [20]:
l

[True, False, True, False, True]

In [ ]:
print(np.ma.array(arr, mask=1)) # Masking entire array

[-- -- -- -- --]


### Reshaping Array

In [22]:
a2

array([[3, 5, 7],
       [4, 7, 9],
       [6, 1, 2]])

In [ ]:
a2.flatten() # Converting 2D to 1D array

array([3, 5, 7, 4, 7, 9, 6, 1, 2])

In [ ]:
a2.reshape(-1) # Converting 2D to 1D array

array([3, 5, 7, 4, 7, 9, 6, 1, 2])

In [25]:
a2.ravel() # Converting 2D to 1D array

array([3, 5, 7, 4, 7, 9, 6, 1, 2])

In [27]:
a1d = np.arange(12)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a1d.reshape(4,3) # Converting 1D to 2D array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
a1d.reshape(2, -1) # Converting 1D to 2D array with automatic column calculation

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
a1d.reshape(-1, 6) # Converting 1D to 2D array with automatic row calculation

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [31]:
a1d.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
a1d.reshape(2, 3, 2) # Converting 1D to 3D array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### Broadcasting of Array

#### Broadcasting is a Powerful machansim in numpy that allows array operations between arrays of Different Shape without copying data.

#### in simple terms:- Broadcasting allows to you automatically expand smaller arrays to match the shape of larger arrays during operations  like addition , multiplication , etc


### Types of Broadcasting

#### 1.Scaler Broadcasting
#### 2.Vactor Broadcasting
#### 3.Matrix Broadcasting

## # 1.Scaler Broadcasting [e.g. Single Element Array]

In [ ]:

 arr

array([10, 15, 20, 25, 30])

In [34]:
# Scaler -> one Element array
s1 = [3]
s2 = 5
s3 = np.array([6])

In [35]:
arr + s1  # Broadcasting s1 to match arr shape

array([13, 18, 23, 28, 33])

In [36]:
arr + s2 # Broadcasting s2 to match arr shape

array([15, 20, 25, 30, 35])

In [37]:
arr + s3 # Broadcasting s3 to match arr shape

array([16, 21, 26, 31, 36])

## 2.Vactor Broadcasting

In [ ]:
a1 = np.array([[1, 2, 3], 
               [4, 5, 6]])

a2 = np.array([[7, 8, 9]])

print(a1 + a2) 

[[ 8 10 12]
 [11 13 15]]


In [39]:
a1 = np.array([[1, 2, 3],
               [4, 5, 6]])

a2 = np.array([10, 20]).reshape(-1, 1)

print(a1 + a2)

a2.shape = (2, 1)

[[11 12 13]
 [24 25 26]]


## 3.Matrix Broadcasting

In [ ]:
a1 = np.array([[1] , [2]]) # 2x1 array
a2 = np.array([[10, 20, 30]]) # 1x3 array

print(a1) 
print()
print(a2)
print()

a3 = a1 + a2 # Broadcasting to 2x3 array
print(a3) 

[[1]
 [2]]

[[10 20 30]]

[[11 21 31]
 [12 22 32]]


: 